---
server:
  address: 'tcp://0.0.0.0:9091/auth'

log:
  level: 'info'

# users stored in /var/lib/authelia/users.yml on the host (not in git)
authentication_backend:
  file:
    path: '/config/users.yml'

access_control:
  default_policy: 'one_factor'

session:
  name: 'authelia_session'
  secret: '{AUTHELIA_SESSION_SECRET}'
  cookies:
    - domain: 'lab.local'
      authelia_url: 'https://lab.local/auth'
      expiration: '1h'
      inactivity: '5m'

storage:
  local:
    path: '/data/db.sqlite3'
  encryption_key: '{AUTHELIA_STORAGE_KEY}'

notifier:
  filesystem:
    filename: '/data/notification.txt'

identity_validation:
  reset_password:
    jwt_secret: '{AUTHELIA_JWT_SECRET}'
