[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
